name: blog
services:
  nginx:
    image: nginx:stable
    container_name: nginx-blog
    ports:
      - "8083:80"
      - "8084:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
      - blog_network

  flask:
    build: ./app
    container_name: flask-blog
    expose:
      - "5000"
    networks:
      - blog_network
    env_file:
      - .env
    volumes:
      - ./app/static:/app/static
      - ./app/templates:/app/templates
    environment:
      - DB_HOST=sqlserver
      - DB_PORT=1437
      - DB_USER=sa
      - DB_PASSWORD=itapadmin*2030
      - DB_NAME=blog
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-blog
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=itapadmin*2030
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=1437
    ports:
      - "1437:1437"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - blog_network
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-blog
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOGFiNTkzOWU0NjUyMDhlMmIwZGFhZDUwNjJhYmUxNTgiLCJ0IjoiNGU4MTVhMDYtYmVjNi00MzYxLWJjODctZGEwYjIyMTk1MzJmIiwicyI6Ik56WXlZV0k1TkRRdE1USmpNUzAwTUdVd0xUZzROell0TURjMFpXWXhOalF3WWpGaiJ9
      - TUNNEL_URL=http://nginx:80
    networks:
      - blog_network
    depends_on:
      - nginx

networks:
  blog_network:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local


